### ISSUE TITLE
Feature request: Sync time with IRL wall clock

### ISSUE THREAD

**Issue by johalun** [DuckyCrayfish/hourglass#50]
It would be pretty cool if day/night could match real life time including times of sunrise and sunset at the server's (or configurable) location. This would of course also mean disabling sleep (or disabling time moving faster when you sleep) but a cool feature I would use on my server :)

Thanks!

**Comment by DuckyCrayfish** [comment]
A feature for syncing the time with the server's timezone is actually already on the to-do list (#1) and will be added with the next major version (maybe by the end of the year?). The idea you had for synchronizing the sunrise and sunset time based on location (since days last longer in some places than other) is something I hadn't thought of, so I appreciate the suggestion :).

I am going to close this issue as it's a duplicate request, but I will add your sunset and sunrise idea to the original ticket.

Thanks!

**Comment by johalun** [comment]
Thank you! Looking forward to it :)
