### ISSUE TITLE
Enhanced Celestials compatibility problem

### ISSUE THREAD

**Issue by GauntAndreX8** [DuckyCrayfish/hourglass#6]
There is a bug with Enchanced Celestial like when I go sleep during bloodmoon I’m in a bed for a sec but later automatically made me leave the bed saying it’s bloodmoon and it causes to forward time a bit more so I suggest like They should only speed up time after the player actually sleeps

**Comment by CorgiTaco** [comment]
Relevant code on my side: https://github.com/CorgiTaco/Enhanced-Celestials/blob/Forge-1.16.X/src/main/java/corgitaco/enhancedcelestials/mixin/MixinLivingEntity.java#L35-L43

**Comment by DuckyCrayfish** [comment]
I was about to go digging, thanks for saving me the trouble @CorgiTaco

**Comment by GauntAndreX8** [comment]
Wait so is the problem fixed or you guys still doing your thing

**Comment by GauntAndreX8** [comment]
When I mean thing I mean still working on it

**Comment by DuckyCrayfish** [comment]
@CorgiTaco I have a suggestion. If you're comfortable having Forge events in your mod (it seems you prefer sponge methods), using the [SleepingTimeCheckEvent](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/event/entity/player/SleepingTimeCheckEvent.java) event will not only prevent time from starting to progress in Hourglass, but it will also prevent the "blinking in an out of bed" effect that currently happens when you try to get in bed during a blood moon. It will instead prevent the player from getting into bed in the first place while presenting them with your red Game Info message, similar to how vanilla handles a player trying to sleep during the day. 

Unfortunately this event does not get called on other LivingEntities like villagers, so this event will have to be implemented alongside either your current method of sleep prevention, or alongside an additional [SleepingLocationCheckEvent](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/event/entity/player/SleepingLocationCheckEvent.java), which is called for villagers.

**Comment by DuckyCrayfish** [comment]
While troubleshooting this issue I noticed that Lunar Event chat notifications will sometimes get sent twice. I'll work on fixing this as well.

**Comment by CorgiTaco** [comment]
Wouldn't the simplest solution here be firing the the boolean I mixin before anything? To me that makes the most sense and it also works on fabric, the reason I've exclusively used mixins here is due to my mod needing to work on both forge + fabric w/ little to no changes.

**Comment by CorgiTaco** [comment]
And on top of that, fabric does not have the mentioned forge events on their side of the fence, so I'm basically forced to use mixin.

**Comment by DuckyCrayfish** [comment]
Ahh, I understand. I did not realize your mod supports Fabric as well.

I agree that your suggestion is the easiest route. Another possibility is delaying time changes until the second tick in bed (more compatible with other Forge exclusive mods that utilize the SleepingLocationCheck).

 I only asked in case the blink effect was something you were interested in preventing.

**Comment by DuckyCrayfish** [comment]
Issue fix released in v1.16.5-1.1.1.1
